[program:persistence-daemon]
command=/usr/local/bin/tsx /opt/deployery/runtime/persistence.ts daemon
autostart=true
autorestart=true
priority=10
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:main]
command=/usr/local/bin/tsx /opt/deployery/runtime/index.ts
autostart=true
autorestart=true
priority=20
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:code-server]
command=/usr/local/bin/code-server /home/user/Desktop --auth none --bind-addr 127.0.0.1:13337
autostart=true
autorestart=true
priority=30
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
user=user
environment=HOME="/home/user",USER="user",LOGNAME="user",SHELL="/bin/bash",PATH="/usr/local/bin:/usr/bin:/bin",VSCODE_PROXY_URI="./proxy/{{port}}"
