#!/usr/bin/env bash
set -euo pipefail

export DEPLOYERY_BASE_URL="${DEPLOYERY_BASE_URL:-http://localhost:3131}"
export DEPLOYERY_SQLITE_PATH="${DEPLOYERY_SQLITE_PATH:-/var/lib/deployery/data/deployery.sqlite}"
export DEPLOYERY_SANDBOX_ROOTFS="${DEPLOYERY_SANDBOX_ROOTFS:-/}"
export DEPLOYERY_SANDBOX_HOME="${DEPLOYERY_SANDBOX_HOME:-/home/user}"
export DEPLOYERY_CODE_SERVER_PORT="${DEPLOYERY_CODE_SERVER_PORT:-13337}"
export DEPLOYERY_SANDBOX_ISOLATION_MODE="${DEPLOYERY_SANDBOX_ISOLATION_MODE:-compatibility}"
export DEPLOYERY_SANDBOX_RUNTIME="${DEPLOYERY_SANDBOX_RUNTIME:-runc}"
export PORT="${PORT:-3131}"

if [ "${DEPLOYERY_SANDBOX_ISOLATION_MODE}" = "hardened-runsc" ]; then
  echo /usr/lib/libmonotonic-shim.so > /etc/ld.so.preload
fi

LEGACY_ROOTFS="/var/lib/deployery/sandbox-rootfs"
FLATTENED_MIGRATION_MARKER="/var/lib/deployery/.flattened-rootfs-migrated"

log_runtime_summary() {
  echo "Deployery sandbox runtime:"
  echo "  isolation mode: ${DEPLOYERY_SANDBOX_ISOLATION_MODE}"
  echo "  requested runtime: ${DEPLOYERY_SANDBOX_RUNTIME}"
  echo "  persistent rootfs: ${DEPLOYERY_SANDBOX_ROOTFS}"
  echo "  sandbox home: ${DEPLOYERY_SANDBOX_HOME}"
}

configure_dns() {
  if [ "${DEPLOYERY_SANDBOX_ISOLATION_MODE}" != "hardened-runsc" ]; then
    return
  fi

  local resolv_conf="/etc/resolv.conf"
  if [ ! -f "${resolv_conf}" ]; then
    return
  fi

  local dns_servers="${DEPLOYERY_SANDBOX_DNS_SERVERS:-}"
  dns_servers="$(printf '%s' "${dns_servers}" | tr ',;' '  ')"

  if [ -z "${dns_servers}" ]; then
    dns_servers="$(
      sed -n 's/^# ExtServers: \[\(.*\)\]/\1/p' "${resolv_conf}" \
        | tr ' ' '\n' \
        | grep -E '^[0-9]{1,3}(\.[0-9]{1,3}){3}$|^[0-9A-Fa-f:]+$' || true \
    )"
    dns_servers="$(
      printf '%s\n' "${dns_servers}" \
        | paste -sd ' ' -
    )"
  fi

  if [ -z "${dns_servers}" ]; then
    dns_servers="1.1.1.1 8.8.8.8"
  fi

  local search_line option_line
  search_line="$(grep -E '^search ' "${resolv_conf}" | head -n 1 || true)"
  option_line="$(grep -E '^options ' "${resolv_conf}" | head -n 1 || true)"

  {
    echo "# Generated by Deployery for hardened runsc mode."
    for nameserver in ${dns_servers}; do
      echo "nameserver ${nameserver}"
    done
    if [ -n "${search_line}" ]; then
      echo "${search_line}"
    fi
    if [ -n "${option_line}" ]; then
      echo "${option_line}"
    fi
  } > "${resolv_conf}"

  echo "Configured hardened DNS servers: ${dns_servers}"
}

preflight_checks() {
  if [ "${DEPLOYERY_SANDBOX_ISOLATION_MODE}" = "hardened-runsc" ] && [ "${DEPLOYERY_SANDBOX_RUNTIME}" != "runsc" ]; then
    echo "Deployery hardened mode requested, but DEPLOYERY_SANDBOX_RUNTIME=${DEPLOYERY_SANDBOX_RUNTIME}. Expected runsc." >&2
  fi
}

migrate_legacy_rootfs() {
  if [ -f "${FLATTENED_MIGRATION_MARKER}" ] || [ ! -d "${LEGACY_ROOTFS}" ]; then
    return
  fi

  if [ ! -d "${LEGACY_ROOTFS}/usr" ]; then
    return
  fi

  echo "Migrating legacy sandbox-rootfs into flattened persistent system volumes..."
  rsync -a "${LEGACY_ROOTFS}/usr/" /usr/
  rsync -a "${LEGACY_ROOTFS}/etc/" /etc/
  rsync -a "${LEGACY_ROOTFS}/opt/" /opt/
  rsync -a "${LEGACY_ROOTFS}/home/user/" /home/user/
  rsync -a --exclude "lib/deployery/" "${LEGACY_ROOTFS}/var/" /var/
  touch "${FLATTENED_MIGRATION_MARKER}"
}

preflight_checks
log_runtime_summary

mkdir -p /var/lib/deployery/data
migrate_legacy_rootfs
configure_dns

/deployery/install-managed-assets.sh
